### ISSUE TITLE
Component classname

### ISSUE THREAD

**Issue by Christilut** [hamed-ehtesham/pretty-checkbox-vue#11]
Thanks for this plugin, makes working with styled radio and checkbox alot easier.

I'd like to request a tiny feature: the top div of a checkbox, radio and toggle should have a class such as `p-check` or `p-radio` in order to distinguish them for CSS purposes.

```
<div data-v-8850ea92="" class="pretty p-default p-round">
  <input type="radio" value="trial">
  <div class="state">
    <label>text</label>
  </div>
</div>
````

Now you can't really tell above whether this is a radio button or checkbox, except from the input type but I'd like to know one level higher what it is.

**Comment by hamed-ehtesham** [comment]
Hi Christiaan,
thanks for using this component,

if i understand you correctly, you can achieve that now and there is no need to change anything
i created a Codepen that shows different ways of doing it:
https://codepen.io/H4M3D3/pen/NBeVJR

**Comment by Christilut** [comment]
Yea that's how I'm doing it now, adding the `p-radio` class to the `p-radio` element. But I have custom styling in a SCSS file and in order to differentiate p-radio and p-check I have to add the class to the element. So that means that with custom styling I always have to add the `p-radio` class to the element of the same name, which seems superfluous to me.

**Comment by Christilut** [comment]
Thanks! 😃

**Comment by hamed-ehtesham** [comment]
you're welcome

i updated Codepen as well
