### ISSUE TITLE
is have checkgroup?? 

### ISSUE THREAD

**Issue by jetBn** [hamed-ehtesham/pretty-checkbox-vue#14]

**Comment by hamed-ehtesham** [comment]
what is checkgroup?

**Comment by jetBn** [comment]
checkboxGroup

**Comment by hamed-ehtesham** [comment]
could you please explain more details about what exactly do you need?

**Comment by jetBn** [comment]
I use in vue then hava need one more to checked .

**Comment by hamed-ehtesham** [comment]
i don't understand you

**Comment by jetBn** [comment]
similar as Element CheckBox  

code:  


<template>
  <el-checkbox-group 
    v-model="checkedCities1"
    :min="1"
    :max="2">
    <el-checkbox v-for="city in cities" :label="city" :key="city">{{city}}</el-checkbox>
  </el-checkbox-group>
</template>
<script>
  const cityOptions = ['上海', '北京', '广州', '深圳'];
  export default {
    data() {
      return {
        checkedCities1: ['上海', '北京'],
        cities: cityOptions
      };
    }
  };
</script>

**Comment by hamed-ehtesham** [comment]
i think this [Codepen](https://codepen.io/H4M3D3/pen/RYdjgp?editors=1010) shows you what you need
