### ISSUE TITLE
How to set checkbox border color?

### ISSUE THREAD

**Issue by yogur** [hamed-ehtesham/pretty-checkbox-vue#16]
How can I set border-color or outline of a checkbox?

**Comment by seaskyways** [comment]
This can be done by setting the SCSS variable ahead of importing the SCSS of pretty-checkbox like so.
```scss
$pretty--color-default: #123456;
@import '~pretty-checkbox/src/pretty-checkbox.scss';
```

**Comment by yogur** [comment]
Ah I see. Can I apply a custom outline color only to a specific checkbox, instead of setting outline color globally?

**Comment by hamed-ehtesham** [comment]
Hi Abed,

this [Codepen](https://codepen.io/H4M3D3/pen/gBxPyy) shows you how
