### ISSUE TITLE
Font-size / icon size

### ISSUE THREAD

**Issue by michaelkunzler** [hamed-ehtesham/pretty-checkbox-vue#17]
Pretty-Checkbox allows to set font-size that turns the Icon bigger. Pretty-checkbox-vue seems not to have an option to trigger this down.

**Comment by hamed-ehtesham** [comment]
Hi @michaelkunzler,

there are examples for it in documentation [here](https://hamed-ehtesham.github.io/pretty-checkbox-vue/#size)
