### ISSUE TITLE
Label position

### ISSUE THREAD

**Issue by marcosrocha85** [hamed-ehtesham/pretty-checkbox-vue#18]
Every day passes by, I came more impressed with this component. Congratulations.

How can I rearrange label on top of checkbox, at right or below of it?

**Comment by hamed-ehtesham** [comment]
Hi Marcos,
thank you for the kind words,

though the real credit goes to @lokesh-coder for base [(CSS) library](https://github.com/lokesh-coder/pretty-checkbox)
and although he watches this repository too but the right place for this question is [his repository](https://github.com/lokesh-coder/pretty-checkbox/issues)

and these following issues are some part of your answer (to place checkbox at right) but to place label on top or below of ckeckbox you should make that happen yourself at the current time
https://github.com/lokesh-coder/pretty-checkbox/issues/34
https://github.com/lokesh-coder/pretty-checkbox/issues/43

**Comment by marcosrocha85** [comment]
Thank you Hamed. Actually I can do that by placing a Label tag outside the p-check, but unfortunately clicking at label does not fire p-check click event unless I do some code.

**Comment by hamed-ehtesham** [comment]
there is no js code needed to fire click event: [example](https://codepen.io/H4M3D3/pen/pQeOQG)
