### ISSUE TITLE
How to catch the input event callback when using pretty checkbox?

### ISSUE THREAD

**Issue by minhtu-cloudtek** [hamed-ehtesham/pretty-checkbox-vue#20]
Hi,

How can I catch input event (such as `@change="myMethod"`) when using pretty checkbox component?

**Comment by hamed-ehtesham** [comment]
Hi @minhtu-cloudtek ,

you can use `@change="myMethod"` with this component and for other methods like `@click` you should use `.native` modifier with them like this: `@click.native="myMethod"`

**Comment by minhtu-cloudtek** [comment]
Many thanks!

It works like a charm!

**Comment by hamed-ehtesham** [comment]
i'm glad i could help you!
