### ISSUE TITLE
Customize colours?

### ISSUE THREAD

**Issue by mmusket** [hamed-ehtesham/pretty-checkbox-vue#21]
What is the best way to customize the colors? 

Looking at pretty-checkbox docs it is done via scss, but since they are packaged in npm I don't see a way to override them.

**Comment by hamed-ehtesham** [comment]
Hello Marco,
i think this would help you: https://github.com/lokesh-coder/pretty-checkbox/issues/38

**Comment by mmusket** [comment]
Thanks Hamed, I'll give this a go. 
Maybe add that to this project's documentation?

**Comment by hamed-ehtesham** [comment]
it is there in `SCSS Customize` section: https://hamed-ehtesham.github.io/pretty-checkbox-vue/#scss-settings

**Comment by mmusket** [comment]
Ok thanks!
