### ISSUE TITLE
Add support for @click

### ISSUE THREAD

**Issue by daniel-stelle** [hamed-ehtesham/pretty-checkbox-vue#7]
Right now, putting a `@click` or `v-on:click` doesn't run the function that it is passed.  I'm not sure if this was intended or not, but there are many circumstances where an on click handler is useful/needed.

**Comment by hamed-ehtesham** [comment]
Hi daniel
thanks for your suggestion
but why don't you use `@change` or `v-on:change` instead?

anyway i intended to make the components just like html default inputs and if that `@click` is supported in theme i will add that feature as soon as possible

**Comment by hamed-ehtesham** [comment]
Hi
i found this conversation which is related to our case here
https://github.com/vuejs/vue/issues/3253
as @AnsonHwang86 suggests there, you can use `.native` modifier if you need listen to `click` event and `@change` isn't suitable for your specific use case

**Comment by reppair** [comment]
Cheers Hamed! `@click.native` is exactly what I used as well.. that way I can disable the `event.target` for the time of the AJAX call and re-enable it later having the result of the request.
It's nice because the checkbox now represents the exact state of the model.attribute in the database :)
