### ISSUE TITLE
p-switch with toggle option is not being animated

### ISSUE THREAD

**Issue by davidjr82** [hamed-ehtesham/pretty-checkbox-vue#8]
With this code, p-switch is not being animated:

`<p-check class="p-switch" toggle>
  On
  <label slot="off-label">Off</label>
</p-check>`

but with this is being animated:

`<p-check class="p-switch">
  On
  <label slot="off-label">Off</label>
</p-check>`

I guess this in not working as expected.

**Comment by hamed-ehtesham** [comment]
Hi @davidjr82 ,

thanks for using this library,

switch animation is not supported in toggle mode, that's how main library ([pretty-checkbox](https://github.com/lokesh-coder/pretty-checkbox)) works and has nothing to do with this library

**Comment by davidjr82** [comment]
Perfect! I was playing with it and I saw that.
Thanks for the answer!
