### ISSUE TITLE
V-MODEL bad result

### ISSUE THREAD

**Issue by Quenway** [hamed-ehtesham/pretty-checkbox-vue#9]
Hi,

I have an issue with the v-model on my pretty checkbox... 

I have 8 checkbox on my page, each of them have different name, id and value... To illustrate my problem and to find some clue, I did add 8 checkbox with the same configuration : 

![image](https://user-images.githubusercontent.com/4678089/42929337-0f4cb9e0-8b3a-11e8-844c-d7b83186d07e.png)

They are bind to a local computed variable which take the data from the state 
`
<input :id="m.module + '-' + h" @change="changeCB" type="checkbox" :value="m.module + '|' + h" v-model="localUser.habilitations"> {{h}}
`
`
<p-check
                        class="p-default p-curve p-smooth"
                        color="primary-o"
                        v-model="localUser.habilitations"
                        @change="changePCB"
                        :value="m.module + '|' + h">{{h}}</p-check>
`

Where localUser is : 
`
localUser: ()-> Object.assign({}, @.$store.getters['user/userById'](@.id))
`

There it is for the environnement. Now let's see what happen when I check / uncheck the checkbox by logging the @.localUser.habilitations in the click event function changeCB and change PCB. I will perform the same action on the checkbox and on the pretty checkbox : 

- uncheck ACCES left, 
- check INSERT left, 
- check ACCES right 
- uncheck SELECT right.

When I check/unchecke the checkboxes

![image](https://user-images.githubusercontent.com/4678089/42929787-6280eefa-8b3b-11e8-8174-0abb72280995.png)

Everything is fine here... But now with the pretty checkbox, I have this result : 

![image](https://user-images.githubusercontent.com/4678089/42929852-9142d3ca-8b3b-11e8-8779-132257c7559d.png)

As you can see, when a uncheck something, i lose 2 entry in my model, and when I check something, there's no change in my model...

Did I misunderstand something or is there a problem with pretty checkbox ?

**Comment by hamed-ehtesham** [comment]
Hi,
thanks for using this component,

i checked your scenario but there was no problem,
could you create a [codepen](https://codepen.io) or github for that?

**Comment by Quenway** [comment]
My first codePen \o/

https://codepen.io/Zorian/pen/WKovLx?editors=1111

**Comment by hamed-ehtesham** [comment]
the problem was this:
https://stackoverflow.com/a/48084145

i changed your code and it works fine now:
https://codepen.io/H4M3D3/pen/djOKJK?editors=1111

**Comment by Quenway** [comment]
OMG Well play dude ! Now i can fully enjoy your component \o/
